.TH MKDF 1 "May 2025" "mkdf 1.0.0" "MKDF User Manual"
.SH NAME
mkdf \- MaKeDir&Files, utility for creating directory and file structures
.SH SYNOPSIS
.B mkdf
[\fIOPTIONS\fR] [\fIEXPRESSION\fR]
.SH DESCRIPTION
.B mkdf
is a utility for quickly creating directory and file structures using either brace expansion syntax or predefined templates.
.PP
If launched without arguments, \fBmkdf\fR starts in interactive mode.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display help information and exit.
.TP
.BR \-v ", " \-\-verbose
Verbose mode. Displays details of each operation.
.TP
.BR \-q ", " \-\-quiet
Quiet mode. Suppresses all output messages.
.TP
.BR \-s ", " \-\-simulate
Simulation mode. Doesn't actually perform creations.
.TP
.BR \-f ", " \-\-force
Force creation even if directories already exist.
.TP
.BR \-i ", " \-\-interactive
Launch MKDF interactive mode.
.TP
.BR \-w ", " \-\-web
Launch the MKDF web interface.
.TP
.BR \-p ", " \-\-port=\fINUMBER\fR
Specify port for the web interface (default: 8080).
.TP
.BR \-c ", " \-\-create=\fIPROJECT\fR \fITEMPLATE\fR
Create a new project based on a predefined template.
.TP
.BR \-\-version
Display MKDF version and exit.
.SH EXPANSION SYNTAX
MKDF uses a brace expansion syntax to efficiently define complex structures:
.PP
- \fB{a,b,c}\fR creates a, b and c at the same level
.PP
- Paths ending with \fB/\fR are created as directories
.PP
- Others are created as empty files
.PP
- You can nest braces: \fB{a/{b,c},d}\fR creates a/b, a/c, and d
.SH PROJECT TEMPLATES
The following project templates are available:
.TP
.B simple
Minimalist structure suitable for small projects.
.TP
.B multi
More complete structure with separation of logical components.
.TP
.B docker
Structure including Docker configuration.
.TP
.B fastapi
Complete structure for a backend application based on FastAPI.
.TP
.B vue-vite
Configuration for a frontend project with Vue.js and Vite.
.TP
.B flask
Structure for a Python web application with Flask.
.TP
.B react
Configuration for a React frontend application.
.SH EXAMPLES
.TP
Create a simple structure:
.BR "mkdf 'project/{src/,docs/,tests/}'"
.TP
Create a more complex structure with nesting:
.BR "mkdf 'project/{src/{models/,views/,controllers/},docs/,tests/{unit/,integration/}}'"
.TP
Create files and directories:
.BR "mkdf 'project/{README.md,src/,docs/USAGE.md}'"
.TP
Create a project from a template:
.BR "mkdf -c my-app react"
.TP
Launch the web interface:
.BR "mkdf --web"
.TP
Launch the web interface on a specific port:
.BR "mkdf --web --port 3000"
.SH FILES
.TP
.I ~/.config/mkdf/config.ini
User configuration file.
.SH SEE ALSO
.BR mkdir (1),
.BR touch (1)
.SH BUGS
Report bugs to <https://github.com/Noziop/mkdf/issues>
.SH AUTHOR
Fassih Belmokhtar <contact@fassih.ch>
.br
https://github.com/Noziop
.SH COPYRIGHT
Copyright \(co 2025 MKDF Contributors
.PP
This program is licensed under the GNU Affero General Public License version 3 (AGPL-3.0) - see the LICENSE file for details.